# Generated by Django 4.1.7 on 2023-03-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_userprofile_confirm_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='confirm_password',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
